cmsDriver.py step1 \
    --filein file:ZTau3Mu_BPH-RunIISummer19UL18GEN-evtgen.root \
    --fileout file:ZTau3Mu_BPH-RunIISummer19UL18SIM-evtgen.root \
    --mc \
    --eventcontent RAWSIM \
    --runUnscheduled \
    --datatier GEN-SIM \
    --conditions 106X_upgrade2018_realistic_v11_L1v1 \
    --beamspot Realistic25ns13TeVEarly2018Collision \
    --step SIM \
    --nThreads 4 \
    --geometry DB:Extended \
    --era Run2_2018 \
    --python ZTau3Mu_SIM.py \
	--no_exec \
    -n -1