cmsDriver.py step1                                  \
  --mc                                              \
  --eventcontent PREMIXRAW                          \
  --runUnscheduled                                  \
  --datatier GEN-SIM-DIGI                           \
  --conditions 106X_upgrade2018_realistic_v11_L1v1  \
  --step DIGI,DATAMIX,L1,DIGI2RAW                   \
  --procModifiers premix_stage2                     \
  --geometry DB:Extended                            \
  --datamix PreMix                                  \
  --era Run2_2018                                   \
  --filein file:SIM.root                            \
  --fileout file:DRPremix.root                      \
  --python_filename pset_DRP.py                     \
  --pileup_input "dbs:/Neutrino_E-10_gun/RunIISummer20ULPrePremix-UL18_106X_upgrade2018_realistic_v11_L1v1-v2/PREMIX" \
  -n -1 --no_exec --nThreads 4